export const CENTRE_LIST_REQUEST = "CENTRE_LIST_REQUEST";
export const CENTRE_LIST_SUCCESS = "CENTRE_LIST_SUCCESS";
export const CENTRE_LIST_FAIL = "CENTRE_LIST_FAIL";

export const CENTRE_DETAILS_REQUEST = "CENTRE_DETAILS_REQUEST";
export const CENTRE_DETAILS_SUCCESS = "CENTRE_DETAILS_SUCCESS";
export const CENTRE_DETAILS_FAIL = "CENTRE_DETAILS_FAIL";

export const CENTRE_REGISTER_REQUEST = "CENTRE_REGISTER_REQUEST";
export const CENTRE_REGISTER_SUCCESS = "CENTRE_REGISTER_SUCCESS";
export const CENTRE_REGISTER_FAIL = "CENTRE_REGISTER_FAIL";

export const CENTRE_DELETE_REQUEST = "CENTRE_DELETE_REQUEST";
export const CENTRE_DELETE_SUCCESS = "CENTRE_DELETE_SUCCESS";
export const CENTRE_DELETE_FAIL = "CENTRE_DELETE_FAIL";

export const CENTRE_UPDATE_REQUEST = "CENTRE_UPDATE_REQUEST";
export const CENTRE_UPDATE_SUCCESS = "CENTRE_UPDATE_SUCCESS";
export const CENTRE_UPDATE_FAIL = "CENTRE_UPDATE_FAIL";
export const CENTRE_UPDATE_RESET = "CENTRE_UPDATE_RESET";
