export const PRICE_LIST_REQUEST = "PRICE_LIST_REQUEST";
export const PRICE_LIST_SUCCESS = "PRICE_LIST_SUCCESS";
export const PRICE_LIST_FAIL = "PRICE_LIST_FAIL";

export const PRICE_DETAILS_REQUEST = "PRICE_DETAILS_REQUEST";
export const PRICE_DETAILS_SUCCESS = "PRICE_DETAILS_SUCCESS";
export const PRICE_DETAILS_FAIL = "PRICE_DETAILS_FAIL";

export const PRICE_REGISTER_REQUEST = "PRICE_REGISTER_REQUEST";
export const PRICE_REGISTER_SUCCESS = "PRICE_REGISTER_SUCCESS";
export const PRICE_REGISTER_FAIL = "PRICE_REGISTER_FAIL";

export const PRICE_DELETE_REQUEST = "PRICE_DELETE_REQUEST";
export const PRICE_DELETE_SUCCESS = "PRICE_DELETE_SUCCESS";
export const PRICE_DELETE_FAIL = "PRICE_DELETE_FAIL";

export const PRICE_UPDATE_REQUEST = "PRICE_UPDATE_REQUEST";
export const PRICE_UPDATE_SUCCESS = "PRICE_UPDATE_SUCCESS";
export const PRICE_UPDATE_FAIL = "PRICE_UPDATE_FAIL";
export const PRICE_UPDATE_RESET = "PRICE_UPDATE_RESET";